### ISSUE TITLE
Assignees and labels shouldn't be an array

### ISSUE THREAD

**Issue by janester** [JasonEtco/create-an-issue#10]
👋I want to start off by saying thank you for writing this action 💖 It's super helpful!

BUT, I found a bug when it comes to adding assignees and labels. Although the frontmatter section of issue templates _appears_ to want a real yaml format, listing the assignees and labels as an array instead of a csv string breaks the template and doesn't automatically add the assignees and labels. Also, when you use the "setup templates" wizard from the settings page in the repo, it will generate a file with csv strings, so I had to modify my template to work with this action 

```diff
- labels: standup
- assignees: bswinnerton, janester, nronas
+ labels: 
+  - standup
+ assignees: 
+  - bswinnerton
+  - janester
+  - nronas
``` 

when my action ran with the old csv format, I got this error

```
For 'properties/assignees', "bswinnerton, janester, nronas" is not an array.
For 'properties/labels', "standup" is not an array.
```

and then I checked your tests and saw that you are expecting yaml arrays

https://github.com/JasonEtco/create-an-issue/blob/57549108a54d43505e2f3b533685e53ed6f19300/tests/fixtures/.github/kitchen-sink.md

But I think this can be easily fixed by just doing a `.split(",")` here

https://github.com/JasonEtco/create-an-issue/blob/57549108a54d43505e2f3b533685e53ed6f19300/index.js#L36-L37

and updating the tests to expect csv strings

cc @JasonEtco

**Comment by JasonEtco** [comment]
Hi @janester! Thank you for the kind words, and for the very helpful details here :pray: Unfortunately, this is born of a difference between the GitHub.com way of doing things and the GitHub API 😬 From [the Issues API docs](https://developer.github.com/v3/issues/#create-an-issue):

<img width="656" alt="image" src="https://user-images.githubusercontent.com/10660468/57080435-84db5c80-6cc0-11e9-99f4-3cdafbf6702d.png">

So I think a good solution would be to use an array if its already an array, or do like you suggested and `.split(',')`. Will have a PR shortly! ✨
