### ISSUE TITLE
unable to update assignees when 'update_existing: true'

### ISSUE THREAD

**Issue by LongOddCode** [JasonEtco/create-an-issue#100]
Hi,

When I set `update_existing: true`, everything is changed except the `assignees`.

**Comment by dblock** [comment]
This looks by design. I'll be happy to add support for things like `update_existing: assignees, labels, body` on top of #112 once that's merged.

**Comment by JasonEtco** [comment]
Hey 👋  this isn't intentional, but it is expected - I'd be open to a PR adding support for updating more than just the body if `update_existing` is `true` and an existing match is found 👍
