### ISSUE TITLE
Atom - saved file data dumped!

### ISSUE THREAD

**Issue by Giov3kajp** [JasonEtco/create-an-issue#102]
I am coding a basic html/css site, saving with ctr+s and viewing on chrome.  There were a few crashes yesterday, but the files reopened to the last saved point.

This morning, when I opened Atom, ALL DATA saved yesterday for both the css and html files were completely gone.  The files were there, and the data from the day previous was there, but all of the progress yesterday was completely gone.  How?? What gives???  How can I prevent this in the future???  

STEPS:
1. Atom is up-to-date 1.58.0 x64
2. Open html file in Atom
3. Open css file in different Atom window
4. Open html in Chrome > inspect
5. Hit ctrl+s a million of times while viewing in Chrome
6. Atom crashes after a couple hours 🙄
7. Reopen files in Atom, saved data is there
8. Atom crashes again a couple hours later 🙄
9. Reopen files again in Atom, saved data is there
10. Atom crashes one more time at the end of the night, I close my Mac and call it a day.
11. Restart Mac in the morning because internet is too slow
12. Open html and css file in Atom
13. Open html in Chrome...and BOOM realised that saved data was gone.😱
14. Searched computer for a temp file, but NG 😭😭😭
15. Report Issue on Github in desperation.😢

Thank you very much for any guidance on understanding what happened and how to prevent something like this in the future! 🙏🏻🙏🏻🙏🏻

**Comment by JasonEtco** [comment]
I believe this issue was opened in error, this repo doesn't have anything to do with Atom. Good luck!
