### ISSUE TITLE
Support timezone

### ISSUE THREAD

**Issue by qianbinbin** [JasonEtco/create-an-issue#105]
Hi Jason,
I have a question, since Github action schedule doesn't support timezone, users around the world have to make some offset for UTC. However, `{{ date | date('dddd, MMMM Do') }}` only use UTC+-0. Is there any way to get the right date?
For example, for timezone UTC+8, I use `0 23 * * *` to schedule at 7:00 everyday, but the date I get is "yesterday".
Thanks in advance!

**Comment by eggplants** [comment]
I tried to specify `TZ` (my timezone is `Asia/Tokyo`) to `env` of JasonEtco/create-an-issue, but it ignored `TZ`.
In `src/action.ts` he uses `Date.now()` to get a present date info. It usually respects `TZ`. But not worked... I don't understand why.

**Comment by JasonEtco** [comment]
You'll have to check within [`nunjucks-date-filter`](https://www.npmjs.com/package/nunjucks-date-filter), which uses `moment.js` to parse and format the date.
