### ISSUE TITLE
Allow templates in labels

### ISSUE THREAD

**Issue by dblock** [JasonEtco/create-an-issue#113]
This didn't work:

```
labels: untriaged, release, v{{ env.VERSION }}
```

<img width="338" alt="Screen Shot 2021-09-23 at 8 20 52 AM" src="https://user-images.githubusercontent.com/542335/134505832-8bcc12f5-9792-489b-93f5-26be1bbe2052.png">

**Comment by JasonEtco** [comment]
Ooh I like that, we should definitely allow this. I'd mean a change here:

https://github.com/JasonEtco/create-an-issue/blob/2fa1fa43001da44050fcb7109647aa315754467c/src/action.ts#L30-L33

Probably something like:

```
labels: listToArray(attributes.labels).map(label => env.renderString(label, templateVariables)
```

And then use `template.labels` in the final issue payload. This seems complicated in conjunction with #100, when issue labels will require _removing_ labels as well as adding them, but we can cross that bridge when we get to it.

**Comment by JasonEtco** [comment]
Looks like there's already a PR for this in progress: #95

**Comment by dblock** [comment]
Finished in #119

**Comment by dblock** [comment]
This is fixed in https://github.com/dblock/create-a-github-issue, a maintained fork.
