### ISSUE TITLE
An error occurred while creating the issue. body is too long (maximum is 65536 characters)

### ISSUE THREAD

**Issue by mikeparker** [JasonEtco/create-an-issue#123]
```
An error occurred while creating the issue. This might be caused by a malformed issue title, or a typo in the labels or assignees. Check ./results.md!

Validation Failed: {"resource":"Issue","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"}
```

Can we trim any payload to the max length before submission?

Or even have an option to overflow the content to a reply after the issue is created, even better.

**Comment by JasonEtco** [comment]
👋 I think that's out of scope for this action - I'm hesitant to add more functionality to what should be a straightforward, reusable action. This feels like a very specific edge-case so I doubt the majority of people would use an option to truncate the body or overflow to a reply.

You could do that yourself with a more complex action, including by using the `outputs` of this one to create the issue then, after having "overflowed" the content yourself, reply with the remaining characters.

**Comment by mikeparker** [comment]
I agree this should be a straightforward action that you can use easily without worrying about edge cases, which is why I think the trimming should be done in the action rather than blowing up if the input is too long.

For me, I'm using this for a weekly report which was written by someone else who no longer works here, it has worked for a long time, and now it's breaking so I need to go into the code to trim the input (which has involved looking up how many bytes per character - which format we're using, UTF standards, etc..). I think most people would rather the action 'just work' and create the issue if the input is too long rather than blowing up. People will need to do the length check manually if its not done in the action so i'm sure over time there will be more people writing the exact same code as me outside the action which feels like a waste.
