### ISSUE TITLE
Archive repo, direct to maintained fork

### ISSUE THREAD

**Issue by dblock** [JasonEtco/create-an-issue#132]
A few months ago I have forked and have been actively maintaining https://github.com/dblock/create-a-github-issue. There has been a release with a number of bug fixes. Will gladly continue doing so, please feel free to open issue/contribute to that repo.

**Comment by JasonEtco** [comment]
I'm still releasing features/bug fixes here as needed. Folks are welcome to use your fork if they find it's better maintained or has features that this one doesn't. Have a nice day 😊
