### ISSUE TITLE
Release v2.8.0 to v2 tag

### ISSUE THREAD

**Issue by Nemo157** [JasonEtco/create-an-issue#138]
I was wondering why my actions were still getting the Node 12 warning despite #136 having been fixed for 15 days in v2.8.0, until I realised that actions doesn't actually use versioning and relies on mutable tags and the `v2` tag is still pointing at the same commit as `v2.6.0`. Will you update this tag, or should I update my workflows to use `v2.8.0` directly?

**Comment by IdiosApps** [comment]
@JasonEtco I'm still seeing this:

```
- uses: JasonEtco/create-an-issue@v2
```

A successful run of the Action gives:

![image](https://user-images.githubusercontent.com/12559216/216185724-5f7bc13a-5c3c-4b19-9804-2d939a3f8997.png)

I have never published an Action before, but it does seem a bit weird as I see a V2 tag that corresponds to v2.9 / v2.9.1 (all the same hash, `e27dddc`).
It seems having this tag wasn't enough?

**Comment by JasonEtco** [comment]
@IdiosApps that warning is in reference to `actions/checkout` - you'll want to update your workflow to point to `actions/checkout@v3`.

**Comment by IdiosApps** [comment]
> @IdiosApps that warning is in reference to `actions/checkout` - you'll want to update your workflow to point to `actions/checkout@v3`.

D'oh! 
I copy pasted from https://github.com/JasonEtco/create-an-issue/blob/main/README.md, and obviously didn't read the error message 😅 I'll raise a PR :)

---

I see your workflows are on `actions/checkout@v3` 👍.
I added a lot of GitHub Action dependabots before, seeing repos using older Action versions. If you want, I can raise a PR for that with [my dependabot-discovery script](https://github.com/IdiosApps/dependabot-discovery). It'd help when `checkout@v4` is out - but wouldn't update the readme unfortunately.
