### ISSUE TITLE
`set-output` command is deprecated and will be disabled soon

### ISSUE THREAD

**Issue by SteveBox0** [JasonEtco/create-an-issue#139]
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by jdblischak** [comment]
I removed this warning by updating from `@v2` to `@v2.8.0`. See Issue #138
