### ISSUE TITLE
v2.9.0 is breaking change; issue template must contain `name` and `about`, but disallowd.

### ISSUE THREAD

**Issue by ndxbn** [JasonEtco/create-an-issue#145]
according to [this document](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), issue templates must contain valid `name:` and `about:` keys in the YAML frontmatter for issue templates defined in `.md` files.
But v2.9.0 disallows theirs.

I tried to remove `name` and `about` keys in my issue template, GitHub says it template is invalid.
https://github.com/ndxbn/ndxbn/pull/1403

**Comment by JasonEtco** [comment]
Ah thanks for the issue @ndxbn, I was worried about that. I've opened #146 to fix the problem by adding `name` and `about` to the accepted fields.

**Comment by JasonEtco** [comment]
I've released a new version, v2.9.1, that includes those fields. Let me know if you're still seeing an issue!
