### ISSUE TITLE
Open issue based on issue comment

### ISSUE THREAD

**Issue by brianamarie** [JasonEtco/create-an-issue#15]
👋 Hi @JasonEtco! I'm looking for an action to open an issue based on a template when there's an issue comment. Ex: We're done with some phase of a project, and we'd like to comment `/open-issue PHASE PROJECT-NAME` and have an issue be created from a template, with the project name, and also ideally linking back to the issue where the comment was created.

Is this action tweak-able to do that? Or, would we need to create a new action to accomplish that?

**Comment by JasonEtco** [comment]
Definitely kind of! One could trigger this action on an issue comment no problem, but the granularity of only reacting to the `/open-issue` "command" is outside of this action's capabilities.

However, there's a [helper `.command` available in `actions-toolkit`](https://github.com/JasonEtco/actions-toolkit#toolscommandcommand-args-match--promise) - one could rewrite this action to use that.

**Comment by brianamarie** [comment]
Awesome, thank you @JasonEtco! I think I'm going to open an issue internally asking for help on this. 😊
