### ISSUE TITLE
using payload vars in assignee

### ISSUE THREAD

**Issue by osallou** [JasonEtco/create-an-issue#16]
Hi,
I using {{ payload.sender.login }} in assigneed template, it fails
Works fine with "hard coded" user id.

Example template:

    ---
    title: test
    assignees: {{ payload.sender.login }}
    labels: bug, enhancement
    ---
    Someone just pushed: {{ payload.sender.login }}

frontmatter header is not parsed. Adding quotes does not help.
Would be nice to get away to assign issue from input vars

Action log:

    debug     Reading from file .github/create_account.md
    info      Front matter for .github/create_account.md is { title: 'NEw push, new task...',
      assignees: { '[object Object]': null },
      labels: 'bug, enhancement' }
     debug     Templates compiled { body: 'Someone just pushed, oh no! Here\'s who did it: XXX\n',
      title: 'NEw push, new task...' }
     info      Creating new issue NEw push, new task...
     error     An error occurred while creating the issue. This might be caused by a malformed issue title, or a typo in the labels or assignees. Check .github/create_account.md!
     error     TypeError: list.split is not a function 
        at listToArray (/index.js:8:44)
        at Toolkit.run (/index.js:42:18)
        at Function.<anonymous> (/node_modules/actions-toolkit/lib/index.js:107:31)
        at step (/node_modules/actions-toolkit/lib/index.js:43:23)
        at Object.next (/node_modules/actions-toolkit/lib/index.js:24:53)
        at /node_modules/actions-toolkit/lib/index.js:18:71
        at new Promise (<anonymous>)
        at __awaiter (/node_modules/actions-toolkit/lib/index.js:14:12)
        at Function.Toolkit.run (/node_modules/actions-toolkit/lib/index.js:98:16)
        at Object.<anonymous> (/index.js:11:9)

**Comment by JasonEtco** [comment]
Hi @osallou 👋 This behaviour isn't supported; using template variables currently only works in the `title` and `body`, here's that code:

https://github.com/JasonEtco/create-an-issue/blob/4ec015aad67f1e9c2f8b6658e1628a2d703b85cb/index.js#L29-L32

I do think that it _should_ work though - would love a PR to add this if you're up for it!

**Comment by valerioBri** [comment]
https://github.com/JasonEtco/create-an-issue/issues/16#issuecomment-519999846
