### ISSUE TITLE
You're using an old version of issue templates

### ISSUE THREAD

**Issue by TomasHubelbauer** [JasonEtco/create-an-issue#17]
GitHub tells me that putting templates in `.github/ISSUE_TEMPLATE.md` and that I should follow https://help.github.com/en/articles/about-issue-and-pull-request-templates to learn how to do it right.

It looks like the recommended way to do this now is to place individual MD files into `.github/ISSUE_TEMPLATE` directory (not an MD file).

You kind of touch on this in the Custom Templates section of the README but I wonder if the default where this action looks should be `.github/ISSUE_TEMPLATES/whatever.md` and not `.github/ISSUE_TEMPLATE.md`. What do you think?

**Comment by JasonEtco** [comment]
Hey @TomasHubelbauer 👋 Single file `.github/ISSUE_TEMPLATE.md` does still work and probably will for a while, but I see what you mean. Would love a PR updating the examples/documentation here!

**Comment by TomasHubelbauer** [comment]
Coolio, I'll play with actions a bit more (just started looking into them today) and see if I can contrib anything.
