### ISSUE TITLE
Feature: Ability to add project designation

### ISSUE THREAD

**Issue by sover02** [JasonEtco/create-an-issue#27]
Would be great if we could select a project to add this issue to, so that issues created this way can automatically be added to a project.

**Comment by JasonEtco** [comment]
Hello 👋 Sure, that sounds neat. A PR would be great if you're interested. I'd imagine we'd check for a `project` field here:

https://github.com/JasonEtco/create-an-issue/blob/58a4ce24766bd5136c227d458de5ed584555c436/index.js#L27

And then we'd include it in the API call:

https://github.com/JasonEtco/create-an-issue/blob/58a4ce24766bd5136c227d458de5ed584555c436/index.js#L40-L46

**Comment by sover02** [comment]
Ah, I started digging into this today. It seems that tools.github.issues doesn't have the capability to designate a project for the issue, and tools.github doesn't have project support in general.

We'll have to make a raw call to the github API, I think.  Do we still want to implement this?

**Comment by sover02** [comment]
It would seem oktokit's api supports this.
https://octokit.github.io/rest.js/#octokit-routes-projects

**Comment by JasonEtco** [comment]
I'm going to close this out, because its over a year old - feel free to reopen if you're still interested in getting this added!
