### ISSUE TITLE
Template render error: (unknown path)

### ISSUE THREAD

**Issue by mattdavis0351** [JasonEtco/create-an-issue#36]
When using default `filename` the action completes as expected
![image](https://user-images.githubusercontent.com/38021615/70459012-26e9d100-1a68-11ea-93de-98d677da382f.png)

When using non default `filename` the action fails with fatal error
![image](https://user-images.githubusercontent.com/38021615/70458923-fbff7d00-1a67-11ea-99d2-99a48acec541.png)

**Comment by JasonEtco** [comment]
This looks like a template rendering error in your issue template, its pointing to `Line 1, Column 61`!

**Comment by mattdavis0351** [comment]
```
---
name: 'Programs: Stand up notes'
about: 'For the Programs team to log stand up notes'
title: "Programs weekly stand up notes: {{ date | date('MMMM Do') | ('add', 3, 'days') }} - {{ date | date('add', 7, 'days') | date('Do') }}"
labels: 'G: Programs'
assignees: ''
---

## Some markdown

- standup
- notes
- guide
```

**Comment by JasonEtco** [comment]
Ah, thanks for that @mattdavis0351 - looks like an error in the title:

```diff
- title: "Programs weekly stand up notes: {{ date | date('MMMM Do') | ('add', 3, 'days') }} - {{ date | date('add', 7, 'days') | date('Do') }}"
+ title: "Programs weekly stand up notes: {{ date | date('MMMM Do') | date('add', 3, 'days') }} - {{ date | date('add', 7, 'days') | date('Do') }}"
```

**Comment by mattdavis0351** [comment]
perfect.  that solved it.  Thanks!
