### ISSUE TITLE
iOS 13.3 is not compatible with xcode 11.3

### ISSUE THREAD

**Issue by shivani-rana** [JasonEtco/create-an-issue#37]
Hi,

I tried installing an application on iOS device having 13.3 iOS version through appium server
, but it is giving error iOS 13.3 is not compatible with xcode 11.3. can anyone pls help. when I checked support for iOS 13.3, it is saying to be compatible with xcode 11.3 .

could anyone pls help.

**Comment by JasonEtco** [comment]
Hello 👋 this repository is not related to iOS in any way. I'd suggest going through Apple's support!
