### ISSUE TITLE
Help: how we can send another repo string

### ISSUE THREAD

**Issue by RafaelGSS** [JasonEtco/create-an-issue#40]
Checking the script, I see that `...tools.context.repo` uses the current repository. But it can be good to receive another repositories string.

Have a parameter spec to send, or I can create a PR for improving it?

**Comment by JasonEtco** [comment]
Hey @RafaelGSS 👋 I'd be totally open to a PR adding an optional `repository: owner/repo` input, with the default being `GITHUB_REPOSITORY`.

However, it's important to note that the API access token provided by GitHub Actions by default (`GITHUB_TOKEN`) is scoped to the repository its working in; so making API calls to write to another repository will fail with a `401`.

Unfortunately, that means also providing a way to include a second API token (usually a personal access token), so that'd need to be documented and ideally would show a helpful error in the case of a failure.

**Comment by RafaelGSS** [comment]
@JasonEtco Needs another `GITHUB_TOKEN` to create an issue in another repository that `GITHUB_TOKEN` already have access?

**Comment by JasonEtco** [comment]
yep, that's correct. The token provided in `secrets.GITHUB_TOKEN` won't be able to create an issue in a different repository.

**Comment by JasonEtco** [comment]
I'm going to close this due to inactivity, and because I don't think there are any more action items. Please feel free to reopen if I've missed something!

**Comment by tsiegleauq** [comment]
> Hey `@RafaelGSS` wave I'd be totally open to a PR adding an optional `repository: owner/repo` input, with the default being `GITHUB_REPOSITORY`.
> 
> However, it's important to note that the API access token provided by GitHub Actions by default (`GITHUB_TOKEN`) is scoped to the repository its working in; so making API calls to write to another repository will fail with a `401`.
> 
> Unfortunately, that means also providing a way to include a second API token (usually a personal access token), so that'd need to be documented and ideally would show a helpful error in the case of a failure.

Hi @JasonEtco, thank you for creating this action.
Has this behavior changed within the past year? Apparently one could create an issue in another repository by sending a request ( https://docs.github.com/en/rest/reference/issues#create-an-issue ). There seems to be another action that claims to be able to create issues on ther repositories ( https://github.com/marketplace/actions/oction-create-issue ). Did not try that tho.

Are they all under the same condition? Is there a way to "inject" another token in your action to create issues on other repos?
We are working in a poly-repo environment and would like to inform our peers automatically if certain stuff changes.

**Comment by JasonEtco** [comment]
@tsiegleauq 👋 Nothing has changed with respect to this specific option. There's not currently a way to define a different repository. You can set a different token, but that's not really useful on its own. Again, happy to review a PR that adds a `repository: owner/repo` option 😊
