### ISSUE TITLE
Error logging the issue number

### ISSUE THREAD

**Issue by lee-dohm** [JasonEtco/create-an-issue#46]
I have some automation in a private repo that uses this Action, so thank you for building it!

Starting seven days ago, my automation is running into a problem where the issue is created but the Action throws an error after that. Relevant log details:

```text
ℹ  info      Creating new issue Completely fake issue title
✖  error     An error occurred while creating the issue. This might be caused by a malformed issue title, or a typo in the labels or assignees. Check .github/support-news-template.md!
✖  error     TypeError: (s || "").replace is not a function 
    at escapeData (/node_modules/@actions/core/lib/command.js:66:10)
    at Command.toString (/node_modules/@actions/core/lib/command.js:60:35)
    at Object.issueCommand (/node_modules/@actions/core/lib/command.js:23:30)
    at Object.setOutput (/node_modules/@actions/core/lib/core.js:88:15)
    at Toolkit.run (/index.js:49:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

It took me a while to figure out what was going wrong because I thought that the issue creation was throwing the error but still succeeding somehow? But inside the `catch` statement you're calling the `actions-toolkit` logging infrastructure and the stack trace only shows the `actions/toolkit` code. So it would appear that this line is hitting the error:

https://github.com/JasonEtco/create-an-issue/blob/3a07eca3b12de7bb7e439432ea3a6f411b09ae60/index.js#L49

because it is the first line after the issue is created that calls into `core.whatever`. I suspect that `issue.data.number` is no longer returning a `Number` in all cases?

Let me know if you need more information.

**Comment by JasonEtco** [comment]
Thanks for opening this @lee-dohm! I'm guessing that `core.setOuput` _needs_ to take a string, not a number, because it replaces spaces and stuff (apparently):

https://github.com/actions/toolkit/blob/6459481e988198bf53e186abf23350b085b1250f/packages/core/src/command.ts#L71-L81

So, it should probably be:

```diff
- core.setOutput('number', issue.data.number)
+ core.setOutput('number', String(issue.data.number))
```

If you're up for that PR that'd be great, if not I can do it!

**Comment by lee-dohm** [comment]
I'll jump on it 👍
