### ISSUE TITLE
use env variables

### ISSUE THREAD

**Issue by sunt05** [JasonEtco/create-an-issue#51]
Great to know this action!
In addition to the several internal template variables, would it be possible to use `env` variables as well?

**Comment by JasonEtco** [comment]
Hey @sunt05 👋 can you elaborate on why you’d want this? I want to better understand what kind of values you’re looking for!

**Comment by sunt05** [comment]
Hi @JasonEtco,
I’d like the issue more customisable: I think one way to do so is via `env` variables. Then I can pass more info from other steps than the internal ones to this action. 
One scenario I have is I can process a csv file and generate several `env` variables, then they can be used to fill the template `md` for a more informative issue.

**Comment by JasonEtco** [comment]
Gotcha, thanks @sunt05! I'm not opposed, I think that'd be a cool feature. If you're up for a PR, here's where that'd go:

https://github.com/JasonEtco/create-an-issue/blob/7a1eb679863bed8c9aa6c4634e68b9b1af016c8c/index.js#L18-L21

Probably something like this:

```diff
   const templateVariables = {
     ...tools.context,
+    env: process.env,
     date: Date.now()
   }
```

And then it'd need some doc updates and tests!

**Comment by sunt05** [comment]
Thanks for the quick update!
I’ll try to get something in, though I’m not a JS person 😂
