### ISSUE TITLE
Feature: If open issue with same title exist, update it.

### ISSUE THREAD

**Issue by PrinsFrank** [JasonEtco/create-an-issue#63]
We have a scheduled run that generates an issue. We would like to combine it with an existing issue with the same title if it is open. Would you accept a PR for this?

**Comment by JasonEtco** [comment]
Hey @PrinsFrank 👋 thanks for the issue! I'm a little torn - I agree that this functionality would be really good, but I almost think it should live in a separate action. Or, it needs to be opt-in for this action, as an input like `createOrUpdate: boolean`. 

I _think_ I'm leaning towards an option in this Action though, so a PR would be great!

**Comment by collen-kr** [comment]
@PrinsFrank are you planning to contribute this feature? I also have this potential use case. @JasonEtco I fully agree this feature should be opt in only !

**Comment by PrinsFrank** [comment]
@collen-kr We are currently living with the fact that duplicate issues are created by manually closing the older versions of that same issue. It would be nice to have this, and good to hear that we are not the only ones wanting to use this, but this was kinda low on my list. Would you want to look into this? Otherwise I will plan to try to implement it this weekend.

**Comment by JasonEtco** [comment]
Closed by #71 🎉 Thanks @PrinsFrank!
