### ISSUE TITLE
How to use custom date variable?

### ISSUE THREAD

**Issue by ham-burger** [JasonEtco/create-an-issue#66]
I want to use custom date in issue template.

ex) when create future routine works issue

Looking at the read.me, it seems that you can't change anything other than the format.If you have any means, please let me know.

**Comment by JasonEtco** [comment]
@ham-burger I'm not sure I understand - you want to use a specific date? You would just put that in the issue template markdown file.

**Comment by ham-burger** [comment]
@JasonEtco 

https://github.com/JasonEtco/create-an-issue#dates

```
---
title: Weekly Radar {{ date | date('dddd, MMMM Do') }} 
---
What's everyone up to this week?
```

The `date` is today(Sorry, Am I misunderstanding?). But what I want is a date, for example 7 days later.

**Comment by JasonEtco** [comment]
Yep, you're correct, `date` is "today" (whenever the action is run). You can do some basic math within the template:

```
---
title: Weekly Meeting Notes: {{ date | date('MMMM Do') }} - {{ date | date('add', 4, 'days') | date('Do') }}
---
```

This will print a title like:

```
Weekly Meeting Notes: March 9th - 13th 
```

You can read the [nunjucks-date-filter](https://www.npmjs.com/package/nunjucks-date-filter) docs to learn more. I think that answers your question! If it does, please close this issue ✨

**Comment by ham-burger** [comment]
I was able to do what I wanted to do!.Thank you for your help🙇
