### ISSUE TITLE
compiler error encountered processing expression "Console.WriteLine("Hello")" Expression does not produce a value in OpenRPA

### ISSUE THREAD

**Issue by AnkitaRaut50** [JasonEtco/create-an-issue#68]
Hi, I am trying to use Invoke code activity in OpenRPA with code as Console.WriteLine("Hello"). I am getting this error: compiler error encountered processing expression "Console.WriteLine("Hello")" Expression does not produce a value.

Also the output variable created shows : type 'PSOject' is not defined.

I am trying to print Hello in output pane using VB language

**Comment by JasonEtco** [comment]
This does not seem related to this project, I'm going to close it. If I'm mistaken, please reopen.
