### ISSUE TITLE
bug: spread omits class getters

### ISSUE THREAD

**Issue by joshgummersall** [JasonEtco/create-an-issue#72]
I've written a quick demo of the issue in [The Typescript playground](https://www.typescriptlang.org/play?ts=3.9.7#code/MYGwhgzhAEDCD2A7ALgUwB7OgbwFDQOgAcBXAIxAEthiAneI6AXmgHIj6jWBuXfQ0hWrQA5qixjkaWgAoAlDn6FCtcSVqI2k6TyXQAvrkO5gSCFlMoMWFolQB3OEjSZ5vSxHghUAOhDwRGWwfEMsXZH05biA).

Here's the code included inline:

```typescript
class Context {
    public prop = 'prop';

    public get getter() {
        return 'getter';
    }
}

const context = new Context();
console.log({...context});
```

This prints: 
```
{ prop: 'prop' }
```

I noticed this issue while trying to write a Github workflow that creates an issue that references a pull request, i.e., accessing [`context.pullRequest`](https://github.com/JasonEtco/actions-toolkit/blob/main/src/context.ts#L96) inside the issue template, which continually renders as an empty string.

In the meantime, I'm able to get that data via `{{ payload.pull_request.number }}` (mirror the logic in the getter).

**Comment by JasonEtco** [comment]
@joshgummersall 👋 I'm not sure I understand - where are you writing the above JS code, for it to interact with this action? Did you mean to open this issue in https://github.com/JasonEtco/actions-toolkit?

**Comment by joshgummersall** [comment]
Thanks for getting back to me! My apologies on the lack of clarity. The issue is here: https://github.com/JasonEtco/create-an-issue/blob/main/src/action.ts#L17

The spread operator does not include fields defined as getters, so tools.context.pullRequest is never added to the template variables.
