### ISSUE TITLE
This might be caused by a malformed issue title, or a typo in the labels or assignees.

### ISSUE THREAD

**Issue by 1UC1F3R616** [JasonEtco/create-an-issue#73]
- I am getting below error and I have tried many changes in the template file, used default one but getting this error every time.

![image](https://user-images.githubusercontent.com/41824020/99875490-19483f80-2c16-11eb-90ba-e1d118600dfa.png)

- It also says bad credentials, can it be because of token that I am using is missing some required permissions?

- Example Issue template that I used:

```md
---
title: Someone just pushed
assignees: 1uc1f3r616
labels: bug
---
Someone just pushed, oh no! Here's who did it: {{ payload.sender.login }}.
```
- Actions template

```md
on: [pull_request]
name: dependabot bot issue
jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          filename: .github/dependabot.md
```

**Comment by 1UC1F3R616** [comment]
I created my own GitHub Token but now I thought that this might be server-side secret and has to be what you have put in the examples ie. GITHUB_TOKEN only. So I changed it and now error is slightly different
![image](https://user-images.githubusercontent.com/41824020/99877405-fa50aa00-2c23-11eb-8ea2-a5687ae434ac.png)

It's giving `Resource not accessible by integration` error now

**Comment by JasonEtco** [comment]
👋 It's a little unclear, but the GitHub API sometimes returns this if the token doesn't have enough access to:

* Know that that user exists
* Can be assigned to the issue

If the built-in `secrets.GITHUB_TOKEN` works for your use-case, you should use that.

**Comment by chenqhxyz** [comment]
Hi,

I faced the same issue when I tried to use my other account to open an issue on repository owned by this account.

I think one of the reasons is because the `secrets.GITHUB_TOKEN` my other account has doesn't have enough permission to create an issue in the repo belong to current account, right? Any idea to solve this?

Thanks.
