### ISSUE TITLE
date variable parsing? 

### ISSUE THREAD

**Issue by maxstreifeneder** [JasonEtco/create-an-issue#82]
Hey Jason,

thanks for your contribution! :) One question: Do I do anything wrong regarding the date variable? Seems like it can't be resolved in my case. 

https://github.com/maxstreifeneder/actionstests/issues/1
https://github.com/maxstreifeneder/actionstests/blob/main/.github/ISSUE_TEMPLATE/teammeeting.md
https://github.com/maxstreifeneder/actionstests/blob/main/.github/workflows/teammeeting.yml

variable names are appearing in the issue title as they are in the template and don't get parsed, unfortunately. 

Thanks in advance and cheers,
Max

**Comment by JasonEtco** [comment]
It looks like you're using a different action now, which is totally cool - apologies that I wasn't around to help out!
