### ISSUE TITLE
Output to tell whether the issue was created or updated

### ISSUE THREAD

**Issue by sargunv** [JasonEtco/create-an-issue#85]
I'm currently using this in a scheduled workflow to check NPM advisories against our `yarn.lock` and file issues when an advisory applies to our dependencies. We'd rely on Dependabot, but that has a file size limit of 0.5MB and our monorepo lockfile is well beyond that.

I use the `update_existing` option to keep updating the existing issues rather than flooding the repo with new ones. However, I'd like to add the ability to send a Slack message when a new issue is created (but not when one is simply updated). Unfortunately, there's no output from this action that tells my GH Actions job whether the issue was actually created or just updated (or neither).

Would it be possible to get such an output?

**Comment by dblock** [comment]
Anything other than https://github.com/JasonEtco/create-an-issue#outputs still needed for this one?

**Comment by sargunv** [comment]
I no longer need this, but the intention was for an output that tells me whether the issue was created or it was simply updated, not just the id/url of the issue.

**Comment by dblock** [comment]
I think https://github.com/JasonEtco/create-an-issue/pull/112 does it, care to confirm?

**Comment by sargunv** [comment]
Maybe I missed it but I don't see a new output there?

**Comment by dblock** [comment]
I guess I am still confused then. For example, in https://github.com/dblock/opensearch-build/runs/3744299836?check_suite_focus=true I see 

```
✔  success   Existing issue [RELEASE] Release version 2.0.0#24: https://github.com/dblock/opensearch-build/issues/24 found but not updated
```

So what is it that's missing?

**Comment by sargunv** [comment]
#120 looks great, thank you!

**Comment by JasonEtco** [comment]
I'll close this as @dblock has implemented it in their fork, and it hasn't come up other than this issue. If anyone still wants it, happy to review a PR.
