### ISSUE TITLE
Available template variables. 

### ISSUE THREAD

**Issue by konstruktoid** [JasonEtco/create-an-issue#86]
Hi,
according to the README we can set different variables, e.g. `Someone just pushed, oh no! Here's who did it: {{ payload.sender.login }}.`, and the list of available template variables is present at https://github.com/JasonEtco/actions-toolkit#toolscontext.

However, `payload.*` isn't anywhere to be found on https://github.com/JasonEtco/actions-toolkit and when using `{{ tools.context.actor }}: {{ tools.context.sha }}` no information is added to the created issue.

See https://github.com/konstruktoid/ansible-role-hardening/issues/48 and https://github.com/konstruktoid/ansible-role-hardening/runs/1965196550?check_suite_focus=true#step:4:1

**Comment by njimenezotto** [comment]
I can confirm this behavior. I tried to use {{ tools.context.actor }} but is empty.

**Comment by JasonEtco** [comment]
I don't think the documentation is very clear; `tools.context.payload` is available from `actions-toolkit`, and so becomes available in your issue templates as just `{{ payload }}`. So similarly, you'd have `{{ actor }}` and `{{ sha }}`. You can see an example of using `tools.context.action` as `{{ action }}` in [this test](https://github.com/JasonEtco/create-an-issue/blob/4cc79e46650462b59761133ac18126b98c5e8a60/tests/index.test.ts#L76-L82) / [this fixture](https://github.com/JasonEtco/create-an-issue/blob/main/tests/fixtures/.github/variables.md).

PRs welcome for any doc improvements, but I'll go ahead and close this for now.

**Comment by ryan-williams** [comment]
I'm running into this, thought I needed to use `{{ tools.context.workflow }}` in my issue template, but I guess `{{ workflow }}` is right.

I also tried to debug some available vars in the issue template with:
````
```json
{{ toJSON(payload) }}
```
````

[but got](https://github.com/ryan-williams/TileDB-SOMA/actions/runs/14450849095/job/40522932357#step:3:15):
```
Error: (unknown path) [Line 4, Column 9]
  Error: Unable to call `toJSON`, which is undefined or falsey
✖  fatal     Template render error: (unknown path) [Line 4, Column 9] 
  Error: Unable to call `toJSON`, which is undefined or falsey
    at Object._prettifyError (/home/runner/work/_actions/JasonEtco/create-an-issue/v2/dist/index.js:27638:11)
    at /home/runner/work/_actions/JasonEtco/create-an-issue/v2/dist/index.js:25784:[19](https://github.com/ryan-williams/TileDB-SOMA/actions/runs/14450849095/job/40522932357#step:3:20)
```

I'd like to access the workflow filename (not workflow name), haven't figured out how yet though.
